spring:
  application:
    name: giddy  ## 仅仅是项目名,与请求路径中的名称无关 localhost:8090/giddy/helloController/sayhello
  datasource:
    username: 
    password: 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url:
    
    
server:
  port: 8090
  servlet:
    context-path: /giddy  #请求路径中的名称,localhost:8090/giddy/helloController/sayhello 
    
spring:
  thymeleaf:
    cache: false #关闭缓存
