spring:
  application:
    name: giddy  ## 仅仅是项目名,与请求路径中的名称无关 localhost:8090/giddy/helloController/sayhello
#  mvc:
#    static-path-pattern: /static/**
      
  datasource: 
    username: root
    password:
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/giddy?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&allowPublicKeyRetrieval=true
  jpa : # 在控制台打印SQL
    show-sql: true
    hibernate: 
      ddl-auto: none 
  jackson: # 让控制台输出的SQL格式更美观
    serialization:
      indent_output: true
  thymeleaf:
    cache: false #关闭缓存
    prefix: classpath:/ #调整页面路径
    
    
server:
  port: 8090
  servlet:
    context-path: /giddy  #请求路径中的名称,localhost:8090/giddy/helloController/sayhello 

#shiro:
#  loginUrl: /login         # 用户未登录时跳转的请求路径
#  unauthorizedUrl: /unauthorized  # 用户没有访问权限时跳转的请求路径
#  userNativeSessionManager: true
#  sessionManager:
#    cookie:
#      name: BIUSID
          
logging: 
  level: 
    web: DEBUG
    